# AM335x configuration

TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true
TARGET_PROVIDES_INIT_RC := true
TARGET_NO_RADIOIMAGE := true

USE_CAMERA_STUB := true

#BOARD_USES_GENERIC_AUDIO := true
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_ALSA_UTILS := true

BUILD_PV_VIDEO_ENCODERS := 1

TARGET_BOARD_PLATFORM := omap3
TARGET_BOOTLOADER_BOARD_NAME := am335xevm
TARGET_CPU_ABI  := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
ARCH_ARM_HAVE_NEON := true
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER :=true

USES_TI_WL1271_COMPAT := true

# WLAN
ifdef USES_TI_WL1271_COMPAT
BOARD_WLAN_DEVICE             := wl12xx_mac80211
BOARD_SOFTAP_DEVICE           := wl12xx_mac80211
WPA_SUPPLICANT_VERSION      := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER   := NL80211
WIFI_DRIVER_MODULE_PATH     := "/system/etc/wifi/wl12xx_sdio.ko"
WIFI_DRIVER_MODULE_NAME     := "wl12xx_sdio"
endif

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
